/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const CreateEmployeeLazyImport = createFileRoute("/create-employee")();
const IndexLazyImport = createFileRoute("/")();
const EmployeeEmployeeIdLazyImport = createFileRoute("/employee/$employeeId")();

// Create/Update Routes

const CreateEmployeeLazyRoute = CreateEmployeeLazyImport.update({
	id: "/create-employee",
	path: "/create-employee",
	getParentRoute: () => rootRoute,
} as any).lazy(() =>
	import("./routes/create-employee.lazy").then((d) => d.Route),
);

const IndexLazyRoute = IndexLazyImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const EmployeeEmployeeIdLazyRoute = EmployeeEmployeeIdLazyImport.update({
	id: "/employee/$employeeId",
	path: "/employee/$employeeId",
	getParentRoute: () => rootRoute,
} as any).lazy(() =>
	import("./routes/employee.$employeeId.lazy").then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/create-employee": {
			id: "/create-employee";
			path: "/create-employee";
			fullPath: "/create-employee";
			preLoaderRoute: typeof CreateEmployeeLazyImport;
			parentRoute: typeof rootRoute;
		};
		"/employee/$employeeId": {
			id: "/employee/$employeeId";
			path: "/employee/$employeeId";
			fullPath: "/employee/$employeeId";
			preLoaderRoute: typeof EmployeeEmployeeIdLazyImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexLazyRoute;
	"/create-employee": typeof CreateEmployeeLazyRoute;
	"/employee/$employeeId": typeof EmployeeEmployeeIdLazyRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexLazyRoute;
	"/create-employee": typeof CreateEmployeeLazyRoute;
	"/employee/$employeeId": typeof EmployeeEmployeeIdLazyRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexLazyRoute;
	"/create-employee": typeof CreateEmployeeLazyRoute;
	"/employee/$employeeId": typeof EmployeeEmployeeIdLazyRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/create-employee" | "/employee/$employeeId";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/create-employee" | "/employee/$employeeId";
	id: "__root__" | "/" | "/create-employee" | "/employee/$employeeId";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute;
	CreateEmployeeLazyRoute: typeof CreateEmployeeLazyRoute;
	EmployeeEmployeeIdLazyRoute: typeof EmployeeEmployeeIdLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	CreateEmployeeLazyRoute: CreateEmployeeLazyRoute,
	EmployeeEmployeeIdLazyRoute: EmployeeEmployeeIdLazyRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-employee",
        "/employee/$employeeId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-employee": {
      "filePath": "create-employee.lazy.tsx"
    },
    "/employee/$employeeId": {
      "filePath": "employee.$employeeId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
